/// Auto-generated legacy state mirror from global_defs.rs legacy global declarations.
///
/// This is an intermediate migration container used to move global mutable state
/// into explicit model-owned state before removing global access sites.
use ndarray::{Array1, Array2, Array3};
use std::sync::{LazyLock, RwLock};

#[derive(Debug, Clone)]
pub struct LegacyGlobalState {
    pub day_emerge: i32,
    pub day_end_mulch: i32,
    pub day_finish: i32,
    pub day_first_def: i32,
    pub day_of_simulation: i32,
    pub daynum: i32,
    pub day_plant: i32,
    pub day_start: i32,
    pub day_start_mulch: i32,
    pub day_start_pred_irrig: i32,
    pub day_stop_pred_irrig: i32,
    pub first_bloom: i32,
    pub first_square: i32,
    pub irrig_method: i32,
    pub isw: i32,
    pub iyear: i32,
    pub kday: i32,
    pub kday_adjust: i32,
    pub last_irrigation: i32,
    pub last_taproot_layer: i32,
    pub location_column_drip: i32,
    pub location_layer_drip: i32,
    pub main_stem_nodes: i32,
    pub min_days_between_irrig: i32,
    pub mulch_indicator: i32,
    pub nk: i32,
    pub nl: i32,
    pub noitr: i32,
    pub num_abscised_leaves: i32,
    pub num_adjust_days: i32,
    pub num_fruit_sites: i32,
    pub num_irrigations: i32,
    pub num_layers_with_roots: i32,
    pub num_pre_fru_nodes: i32,
    pub num_root_age_groups: i32,
    pub num_shedding_tags: i32,
    pub num_veg_branches: i32,
    pub plant_row_column: i32,
    pub water_table_layer: i32,
    pub defoliation_date: Array1<i32>,
    pub defoliation_method: Array1<i32>,
    pub fruiting_code: Array3<i32>,
    pub lateral_root_flag: Array1<i32>,
    pub num_fruit_branches: Array1<i32>,
    pub num_nodes: Array2<i32>,
    pub node_layer: Array2<i32>,
    pub node_layer_pre_fru: Array1<i32>,
    pub root_col_num_left: Array1<i32>,
    pub root_col_num_right: Array1<i32>,
    pub soil_horizon_num: Array1<i32>,
    pub b_end: bool,
    pub b_pollin_switch: bool,
    pub nadj: Array1<bool>,
    pub abscised_fruit_sites: f64,
    pub abscised_leaf_weight: f64,
    pub actual_boll_growth: f64,
    pub actual_burr_growth: f64,
    pub actual_square_growth: f64,
    pub actual_soil_evaporation: f64,
    pub actual_stem_growth: f64,
    pub actual_transpiration: f64,
    pub addwtbl: f64,
    pub adj_add_height_rate: f64,
    pub adj_add_ms_nodes_rate: f64,
    pub adj_add_sites_rate: f64,
    pub adj_green_boll_absc: f64,
    pub adj_square_absc: f64,
    pub applied_water: f64,
    pub average_lwp: f64,
    pub average_lwp_min: f64,
    pub average_soil_psi: f64,
    pub avrg_daily_temp: f64,
    pub bloom_weight_loss: f64,
    pub burr_n_conc: f64,
    pub burr_nitrogen: f64,
    pub burr_weight_green_bolls: f64,
    pub burr_weight_open_bolls: f64,
    pub carbon_allocated_for_root_growth: f64,
    pub carbon_stress: f64,
    pub conmax: f64,
    pub cotton_weight_green_bolls: f64,
    pub cotton_weight_open_bolls: f64,
    pub cum_evaporation: f64,
    pub cum_fertilizer_n: f64,
    pub cum_net_photosynth: f64,
    pub cum_nitrogen_uptake: f64,
    pub cum_plant_n_loss: f64,
    pub cum_transpiration: f64,
    pub cum_water_added: f64,
    pub cum_water_drained: f64,
    pub daily_root_loss: f64,
    pub day_inc: f64,
    pub day_time_temp: f64,
    pub dclay: f64,
    pub deep_soil_temperature: f64,
    pub density_factor: f64,
    pub depth_last_root_layer: f64,
    pub dsand: f64,
    pub el_cond_sat_soil_today: f64,
    pub extra_carbon: f64,
    pub fruit_growth_ratio: f64,
    pub ginp: f64,
    pub gintot: f64,
    pub green_bolls_lost: f64,
    pub initial_total_soil_water: f64,
    pub irrigation_depth: f64,
    pub leaf_area_index: f64,
    pub leaf_n_conc: f64,
    pub leaf_nitrogen: f64,
    pub leaf_weight_area_ratio: f64,
    pub light_intercept: f64,
    pub lint_yield: f64,
    pub lwp_max: f64,
    pub lwp_min: f64,
    pub max_irrigation: f64,
    pub mineralized_organic_n: f64,
    pub mulch_tran_lw: f64,
    pub mulch_tran_sw: f64,
    pub net_photosynthesis: f64,
    pub night_time_temp: f64,
    pub nitrogen_stress: f64,
    pub n_stress_fruiting: f64,
    pub n_stress_roots: f64,
    pub n_stress_veg: f64,
    pub num_green_bolls: f64,
    pub num_open_bolls: f64,
    pub num_squares: f64,
    pub percent_defoliation: f64,
    pub per_plant_area: f64,
    pub petiole_n_conc: f64,
    pub petiole_nitrogen: f64,
    pub petiole_no3_n_conc: f64,
    pub pixcon: f64,
    pub pixda: f64,
    pub pixdn: f64,
    pub pixdz: f64,
    pub pix_in_plants: f64,
    pub plant_height: f64,
    pub plant_population: f64,
    pub plant_row_location: f64,
    pub plant_weight: f64,
    pub plant_weight_at_start: f64,
    pub pot_gro_all_bolls: f64,
    pub pot_gro_all_burrs: f64,
    pub pot_gro_all_leaves: f64,
    pub pot_gro_all_petioles: f64,
    pub pot_gro_all_roots: f64,
    pub pot_gro_all_squares: f64,
    pub pot_gro_stem: f64,
    pub ratio_implicit: f64,
    pub reference_transp: f64,
    pub reserve_c: f64,
    pub rn: f64,
    pub root_n_conc: f64,
    pub root_nitrogen: f64,
    pub root_weight_loss: f64,
    pub row_space: f64,
    pub seed_n_conc: f64,
    pub seed_nitrogen: f64,
    pub soil_nitrogen_at_start: f64,
    pub soil_nitrogen_loss: f64,
    pub square_n_conc: f64,
    pub square_nitrogen: f64,
    pub stem_n_conc: f64,
    pub stem_nitrogen: f64,
    pub sum_no3_n90: f64,
    pub supply_nh4_n: f64,
    pub supply_no3_n: f64,
    pub tap_root_length: f64,
    pub total_actual_leaf_growth: f64,
    pub total_actual_petiole_growth: f64,
    pub total_petiole_weight: f64,
    pub total_required_n: f64,
    pub total_root_weight: f64,
    pub total_soil_nh4_n: f64,
    pub total_soil_nitrogen: f64,
    pub total_soil_no3_n: f64,
    pub total_soil_urea_n: f64,
    pub total_soil_water: f64,
    pub total_square_weight: f64,
    pub total_stem_weight: f64,
    pub water_stress: f64,
    pub water_stress_stem: f64,
    pub abscission_lag: Array1<f64>,
    pub actual_root_growth: Array2<f64>,
    pub age_of_boll: Array3<f64>,
    pub age_of_pre_fru_node: Array1<f64>,
    pub age_of_site: Array3<f64>,
    pub airdr: Array1<f64>,
    pub air_temp: Array1<f64>,
    pub albedo: Array1<f64>,
    pub alpha: Array1<f64>,
    pub avrg_node_temper: Array3<f64>,
    pub average_leaf_age: Array1<f64>,
    pub beta: Array1<f64>,
    pub boll_weight: Array3<f64>,
    pub bulk_density: Array1<f64>,
    pub burr_weight: Array3<f64>,
    pub cgind: Array1<f64>,
    pub clay_volume_fraction: Array1<f64>,
    pub cloud_cover_ratio: Array1<f64>,
    pub cloud_type_corr: Array1<f64>,
    pub defoliant_app_rate: Array1<f64>,
    pub delay_new_fru_branch: Array1<f64>,
    pub delay_new_node: Array2<f64>,
    pub dew_point_temp: Array1<f64>,
    pub dl: Array1<f64>,
    pub es1hour: Array1<f64>,
    pub es2hour: Array1<f64>,
    pub field_capacity: Array1<f64>,
    pub foliage_temp: Array1<f64>,
    pub fresh_organic_matter: Array2<f64>,
    pub fresh_organic_nitrogen: Array2<f64>,
    pub fruit_fraction: Array3<f64>,
    pub heat_capacity_soil_solid: Array1<f64>,
    pub heat_cond_dry_soil: Array1<f64>,
    pub humus_nitrogen: Array2<f64>,
    pub humus_organic_matter: Array2<f64>,
    pub leaf_age: Array3<f64>,
    pub leaf_area_main_stem: Array2<f64>,
    pub leaf_area: Array1<f64>,
    pub leaf_area_indexes: Array1<f64>,
    pub leaf_area_nodes: Array3<f64>,
    pub leaf_area_pre_fru: Array1<f64>,
    pub leaf_weight_layer: Array1<f64>,
    pub leaf_weight_main_stem: Array2<f64>,
    pub leaf_weight_nodes: Array3<f64>,
    pub leaf_weight_pre_fru: Array1<f64>,
    pub light_intercept_layer: Array1<f64>,
    pub lwp_min_x: Array1<f64>,
    pub lwp_x: Array1<f64>,
    pub marginal_water_content: Array1<f64>,
    pub max_water_capacity: Array1<f64>,
    pub mulch_temp: Array1<f64>,
    pub no3_flow_fraction: Array1<f64>,
    pub petiole_weight_main_stem: Array2<f64>,
    pub petiole_weight_nodes: Array3<f64>,
    pub petiole_weight_pre_fru: Array1<f64>,
    pub pore_space: Array1<f64>,
    pub pot_gro_bolls: Array3<f64>,
    pub pot_gro_burrs: Array3<f64>,
    pub pot_gro_leaf_area_main_stem: Array2<f64>,
    pub pot_gro_leaf_area_nodes: Array3<f64>,
    pub pot_gro_leaf_area_pre_fru: Array1<f64>,
    pub pot_gro_leaf_weight_main_stem: Array2<f64>,
    pub pot_gro_leaf_weight_nodes: Array3<f64>,
    pub pot_gro_leaf_weight_pre_fru: Array1<f64>,
    pub pot_gro_petiole_weight_main_stem: Array2<f64>,
    pub pot_gro_petiole_weight_nodes: Array3<f64>,
    pub pot_gro_petiole_weight_pre_fru: Array1<f64>,
    pub pot_gro_roots: Array2<f64>,
    pub pot_gro_squares: Array3<f64>,
    pub radiation: Array1<f64>,
    pub reference_etp: Array1<f64>,
    pub relative_humidity: Array1<f64>,
    pub rlat1: Array1<f64>,
    pub rlat2: Array1<f64>,
    pub root_age: Array2<f64>,
    pub root_gro_factor: Array2<f64>,
    pub root_impede: Array2<f64>,
    pub root_weight: Array3<f64>,
    pub root_wt_capbl_uptake: Array2<f64>,
    pub sand_volume_fraction: Array1<f64>,
    pub saturated_hyd_cond: Array1<f64>,
    pub shed_by_carbon_stress: Array1<f64>,
    pub shed_by_nitrogen_stress: Array1<f64>,
    pub shed_by_water_stress: Array1<f64>,
    pub soil_psi: Array2<f64>,
    pub soil_temp: Array2<f64>,
    pub soil_temp_daily_avrg: Array2<f64>,
    pub square_weight: Array3<f64>,
    pub stem_weight: Array1<f64>,
    pub thad: Array1<f64>,
    pub thetar: Array1<f64>,
    pub thetas: Array1<f64>,
    pub thts: Array1<f64>,
    pub var_par: Array1<f64>,
    pub vol_nh4_n_content: Array2<f64>,
    pub vol_no3_n_content: Array2<f64>,
    pub vol_urea_n_content: Array2<f64>,
    pub vol_water_content: Array2<f64>,
    pub wind_speed: Array1<f64>,
    pub wk: Array1<f64>,
}

impl Default for LegacyGlobalState {
    fn default() -> Self {
        Self {
            day_emerge: 0,
            day_end_mulch: 0,
            day_finish: 0,
            day_first_def: 0,
            day_of_simulation: 0,
            daynum: 0,
            day_plant: 0,
            day_start: 0,
            day_start_mulch: 0,
            day_start_pred_irrig: 0,
            day_stop_pred_irrig: 0,
            first_bloom: 0,
            first_square: 0,
            irrig_method: 0,
            isw: 0,
            iyear: 0,
            kday: 0,
            kday_adjust: 0,
            last_irrigation: 0,
            last_taproot_layer: 0,
            location_column_drip: 0,
            location_layer_drip: 0,
            main_stem_nodes: 0,
            min_days_between_irrig: 0,
            mulch_indicator: 0,
            nk: 0,
            nl: 0,
            noitr: 0,
            num_abscised_leaves: 0,
            num_adjust_days: 0,
            num_fruit_sites: 0,
            num_irrigations: 0,
            num_layers_with_roots: 0,
            num_pre_fru_nodes: 0,
            num_root_age_groups: 0,
            num_shedding_tags: 0,
            num_veg_branches: 0,
            plant_row_column: 0,
            water_table_layer: 0,
            defoliation_date: Array1::from_elem(5, 0),
            defoliation_method: Array1::from_elem(5, 0),
            fruiting_code: Array3::from_elem((3, 30, 5), 0),
            lateral_root_flag: Array1::from_elem(40, 0),
            num_fruit_branches: Array1::from_elem(3, 0),
            num_nodes: Array2::from_elem((3, 30), 0),
            node_layer: Array2::from_elem((3, 30), 0),
            node_layer_pre_fru: Array1::from_elem(9, 0),
            root_col_num_left: Array1::from_elem(40, 0),
            root_col_num_right: Array1::from_elem(40, 0),
            soil_horizon_num: Array1::from_elem(40, 0),
            b_end: false,
            b_pollin_switch: false,
            nadj: Array1::from_elem(5, false),
            abscised_fruit_sites: 0.0,
            abscised_leaf_weight: 0.0,
            actual_boll_growth: 0.0,
            actual_burr_growth: 0.0,
            actual_square_growth: 0.0,
            actual_soil_evaporation: 0.0,
            actual_stem_growth: 0.0,
            actual_transpiration: 0.0,
            addwtbl: 0.0,
            adj_add_height_rate: 0.0,
            adj_add_ms_nodes_rate: 0.0,
            adj_add_sites_rate: 0.0,
            adj_green_boll_absc: 0.0,
            adj_square_absc: 0.0,
            applied_water: 0.0,
            average_lwp: 0.0,
            average_lwp_min: 0.0,
            average_soil_psi: 0.0,
            avrg_daily_temp: 0.0,
            bloom_weight_loss: 0.0,
            burr_n_conc: 0.0,
            burr_nitrogen: 0.0,
            burr_weight_green_bolls: 0.0,
            burr_weight_open_bolls: 0.0,
            carbon_allocated_for_root_growth: 0.0,
            carbon_stress: 0.0,
            conmax: 0.0,
            cotton_weight_green_bolls: 0.0,
            cotton_weight_open_bolls: 0.0,
            cum_evaporation: 0.0,
            cum_fertilizer_n: 0.0,
            cum_net_photosynth: 0.0,
            cum_nitrogen_uptake: 0.0,
            cum_plant_n_loss: 0.0,
            cum_transpiration: 0.0,
            cum_water_added: 0.0,
            cum_water_drained: 0.0,
            daily_root_loss: 0.0,
            day_inc: 0.0,
            day_time_temp: 0.0,
            dclay: 0.0,
            deep_soil_temperature: 0.0,
            density_factor: 0.0,
            depth_last_root_layer: 0.0,
            dsand: 0.0,
            el_cond_sat_soil_today: 0.0,
            extra_carbon: 0.0,
            fruit_growth_ratio: 0.0,
            ginp: 0.0,
            gintot: 0.0,
            green_bolls_lost: 0.0,
            initial_total_soil_water: 0.0,
            irrigation_depth: 0.0,
            leaf_area_index: 0.0,
            leaf_n_conc: 0.0,
            leaf_nitrogen: 0.0,
            leaf_weight_area_ratio: 0.0,
            light_intercept: 0.0,
            lint_yield: 0.0,
            lwp_max: 0.0,
            lwp_min: 0.0,
            max_irrigation: 0.0,
            mineralized_organic_n: 0.0,
            mulch_tran_lw: 0.0,
            mulch_tran_sw: 0.0,
            net_photosynthesis: 0.0,
            night_time_temp: 0.0,
            nitrogen_stress: 0.0,
            n_stress_fruiting: 0.0,
            n_stress_roots: 0.0,
            n_stress_veg: 0.0,
            num_green_bolls: 0.0,
            num_open_bolls: 0.0,
            num_squares: 0.0,
            percent_defoliation: 0.0,
            per_plant_area: 0.0,
            petiole_n_conc: 0.0,
            petiole_nitrogen: 0.0,
            petiole_no3_n_conc: 0.0,
            pixcon: 0.0,
            pixda: 0.0,
            pixdn: 0.0,
            pixdz: 0.0,
            pix_in_plants: 0.0,
            plant_height: 0.0,
            plant_population: 0.0,
            plant_row_location: 0.0,
            plant_weight: 0.0,
            plant_weight_at_start: 0.0,
            pot_gro_all_bolls: 0.0,
            pot_gro_all_burrs: 0.0,
            pot_gro_all_leaves: 0.0,
            pot_gro_all_petioles: 0.0,
            pot_gro_all_roots: 0.0,
            pot_gro_all_squares: 0.0,
            pot_gro_stem: 0.0,
            ratio_implicit: 0.0,
            reference_transp: 0.0,
            reserve_c: 0.0,
            rn: 0.0,
            root_n_conc: 0.0,
            root_nitrogen: 0.0,
            root_weight_loss: 0.0,
            row_space: 0.0,
            seed_n_conc: 0.0,
            seed_nitrogen: 0.0,
            soil_nitrogen_at_start: 0.0,
            soil_nitrogen_loss: 0.0,
            square_n_conc: 0.0,
            square_nitrogen: 0.0,
            stem_n_conc: 0.0,
            stem_nitrogen: 0.0,
            sum_no3_n90: 0.0,
            supply_nh4_n: 0.0,
            supply_no3_n: 0.0,
            tap_root_length: 0.0,
            total_actual_leaf_growth: 0.0,
            total_actual_petiole_growth: 0.0,
            total_petiole_weight: 0.0,
            total_required_n: 0.0,
            total_root_weight: 0.0,
            total_soil_nh4_n: 0.0,
            total_soil_nitrogen: 0.0,
            total_soil_no3_n: 0.0,
            total_soil_urea_n: 0.0,
            total_soil_water: 0.0,
            total_square_weight: 0.0,
            total_stem_weight: 0.0,
            water_stress: 0.0,
            water_stress_stem: 0.0,
            abscission_lag: Array1::from_elem(20, 0.0),
            actual_root_growth: Array2::from_elem((40, 20), 0.0),
            age_of_boll: Array3::from_elem((3, 30, 5), 0.0),
            age_of_pre_fru_node: Array1::from_elem(9, 0.0),
            age_of_site: Array3::from_elem((3, 30, 5), 0.0),
            airdr: Array1::from_elem(9, 0.0),
            air_temp: Array1::from_elem(24, 0.0),
            albedo: Array1::from_elem(24, 0.0),
            alpha: Array1::from_elem(9, 0.0),
            avrg_node_temper: Array3::from_elem((3, 30, 5), 0.0),
            average_leaf_age: Array1::from_elem(20, 0.0),
            beta: Array1::from_elem(9, 0.0),
            boll_weight: Array3::from_elem((3, 30, 5), 0.0),
            bulk_density: Array1::from_elem(9, 0.0),
            burr_weight: Array3::from_elem((3, 30, 5), 0.0),
            cgind: Array1::from_elem(3, 0.0),
            clay_volume_fraction: Array1::from_elem(40, 0.0),
            cloud_cover_ratio: Array1::from_elem(24, 0.0),
            cloud_type_corr: Array1::from_elem(24, 0.0),
            defoliant_app_rate: Array1::from_elem(5, 0.0),
            delay_new_fru_branch: Array1::from_elem(3, 0.0),
            delay_new_node: Array2::from_elem((3, 30), 0.0),
            dew_point_temp: Array1::from_elem(24, 0.0),
            dl: Array1::from_elem(40, 0.0),
            es1hour: Array1::from_elem(24, 0.0),
            es2hour: Array1::from_elem(24, 0.0),
            field_capacity: Array1::from_elem(40, 0.0),
            foliage_temp: Array1::from_elem(20, 0.0),
            fresh_organic_matter: Array2::from_elem((40, 20), 0.0),
            fresh_organic_nitrogen: Array2::from_elem((40, 20), 0.0),
            fruit_fraction: Array3::from_elem((3, 30, 5), 0.0),
            heat_capacity_soil_solid: Array1::from_elem(40, 0.0),
            heat_cond_dry_soil: Array1::from_elem(40, 0.0),
            humus_nitrogen: Array2::from_elem((40, 20), 0.0),
            humus_organic_matter: Array2::from_elem((40, 20), 0.0),
            leaf_age: Array3::from_elem((3, 30, 5), 0.0),
            leaf_area_main_stem: Array2::from_elem((3, 30), 0.0),
            leaf_area: Array1::from_elem(20, 0.0),
            leaf_area_indexes: Array1::from_elem(20, 0.0),
            leaf_area_nodes: Array3::from_elem((3, 30, 5), 0.0),
            leaf_area_pre_fru: Array1::from_elem(9, 0.0),
            leaf_weight_layer: Array1::from_elem(20, 0.0),
            leaf_weight_main_stem: Array2::from_elem((3, 30), 0.0),
            leaf_weight_nodes: Array3::from_elem((3, 30, 5), 0.0),
            leaf_weight_pre_fru: Array1::from_elem(9, 0.0),
            light_intercept_layer: Array1::from_elem(20, 0.0),
            lwp_min_x: Array1::from_elem(3, 0.0),
            lwp_x: Array1::from_elem(3, 0.0),
            marginal_water_content: Array1::from_elem(40, 0.0),
            max_water_capacity: Array1::from_elem(40, 0.0),
            mulch_temp: Array1::from_elem(20, 0.0),
            no3_flow_fraction: Array1::from_elem(40, 0.0),
            petiole_weight_main_stem: Array2::from_elem((3, 30), 0.0),
            petiole_weight_nodes: Array3::from_elem((3, 30, 5), 0.0),
            petiole_weight_pre_fru: Array1::from_elem(9, 0.0),
            pore_space: Array1::from_elem(40, 0.0),
            pot_gro_bolls: Array3::from_elem((3, 30, 5), 0.0),
            pot_gro_burrs: Array3::from_elem((3, 30, 5), 0.0),
            pot_gro_leaf_area_main_stem: Array2::from_elem((3, 30), 0.0),
            pot_gro_leaf_area_nodes: Array3::from_elem((3, 30, 5), 0.0),
            pot_gro_leaf_area_pre_fru: Array1::from_elem(9, 0.0),
            pot_gro_leaf_weight_main_stem: Array2::from_elem((3, 30), 0.0),
            pot_gro_leaf_weight_nodes: Array3::from_elem((3, 30, 5), 0.0),
            pot_gro_leaf_weight_pre_fru: Array1::from_elem(9, 0.0),
            pot_gro_petiole_weight_main_stem: Array2::from_elem((3, 30), 0.0),
            pot_gro_petiole_weight_nodes: Array3::from_elem((3, 30, 5), 0.0),
            pot_gro_petiole_weight_pre_fru: Array1::from_elem(9, 0.0),
            pot_gro_roots: Array2::from_elem((40, 20), 0.0),
            pot_gro_squares: Array3::from_elem((3, 30, 5), 0.0),
            radiation: Array1::from_elem(24, 0.0),
            reference_etp: Array1::from_elem(24, 0.0),
            relative_humidity: Array1::from_elem(24, 0.0),
            rlat1: Array1::from_elem(40, 0.0),
            rlat2: Array1::from_elem(40, 0.0),
            root_age: Array2::from_elem((40, 20), 0.0),
            root_gro_factor: Array2::from_elem((40, 20), 0.0),
            root_impede: Array2::from_elem((40, 20), 0.0),
            root_weight: Array3::from_elem((40, 20, 3), 0.0),
            root_wt_capbl_uptake: Array2::from_elem((40, 20), 0.0),
            sand_volume_fraction: Array1::from_elem(40, 0.0),
            saturated_hyd_cond: Array1::from_elem(9, 0.0),
            shed_by_carbon_stress: Array1::from_elem(20, 0.0),
            shed_by_nitrogen_stress: Array1::from_elem(20, 0.0),
            shed_by_water_stress: Array1::from_elem(20, 0.0),
            soil_psi: Array2::from_elem((40, 20), 0.0),
            soil_temp: Array2::from_elem((40, 20), 0.0),
            soil_temp_daily_avrg: Array2::from_elem((40, 20), 0.0),
            square_weight: Array3::from_elem((3, 30, 5), 0.0),
            stem_weight: Array1::from_elem(365, 0.0),
            thad: Array1::from_elem(40, 0.0),
            thetar: Array1::from_elem(40, 0.0),
            thetas: Array1::from_elem(9, 0.0),
            thts: Array1::from_elem(40, 0.0),
            var_par: Array1::from_elem(61, 0.0),
            vol_nh4_n_content: Array2::from_elem((40, 20), 0.0),
            vol_no3_n_content: Array2::from_elem((40, 20), 0.0),
            vol_urea_n_content: Array2::from_elem((40, 20), 0.0),
            vol_water_content: Array2::from_elem((40, 20), 0.0),
            wind_speed: Array1::from_elem(24, 0.0),
            wk: Array1::from_elem(20, 0.0),
        }
    }
}

static LEGACY_STATE: LazyLock<RwLock<LegacyGlobalState>> =
    LazyLock::new(|| RwLock::new(LegacyGlobalState::default()));

impl LegacyGlobalState {
    pub fn from_globals() -> Self {
        LEGACY_STATE
            .read()
            .expect("legacy state lock should not be poisoned")
            .clone()
    }

    pub fn read_from_globals(&mut self) {
        *self = Self::from_globals();
    }

    pub fn write_to_globals(&self) {
        *LEGACY_STATE
            .write()
            .expect("legacy state lock should not be poisoned") = self.clone();
    }
}
