[tool.poetry]
name = "cotton2k"
version = "4.0.0a1"
description = "Reimplementation for Cotton2k simulation model"
authors = ["Tang Ziya <tcztzy@gmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.rst"
repository = "https://github.com/tcztzy/cotton2k"
keywords = [
    "cotton", "simulation", "model"
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[tool.poetry.dependencies]
python = "^3.9"
PySimpleGUI = { version = "^4.30", optional = true }

[tool.poetry.dev-dependencies]
pre-commit = "^2.7.1"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"

[tool.poetry.extras]
gui = ["PySimpleGUI"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "invalid-name",
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "unsubscriptable-object",
]

[tool.pylint.FORMAT]
max-line-length = 88
